id: I27E23797
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T10:59:53+00:00'
last_modified: '2022-06-08T08:54:50.625791+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25080
  title: ཤེར་ཕྱིན་མངོན་རྟོགས་རྒྱན་གྱི་འགྲེལ་པ་དང་བཅས་པའི་རྣམ་བཤད་སྙིང་པོའི་རྒྱན་གྱི་དགོངས་དོན་གསལ་བར་བྱེད་པའི་མེ་ལོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    BAE2:
      image_group_id: I1KG25082
      title: ''
      total_pages: 500
      order: 1
      base_file: BAE2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
