id: P009141
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG25080
  title: ཤེར་ཕྱིན་མངོན་རྟོགས་རྒྱན་གྱི་འགྲེལ་པ་དང་བཅས་པའི་རྣམ་བཤད་སྙིང་པོའི་རྒྱན་གྱི་དགོངས་དོན་གསལ་བར་བྱེད་པའི་མེ་ལོང་།
  author: ''
  volumes:
    7bd53522877d4a61b02523bed9f08d2f:
      image_group_id: I1KG25082
      title: ''
      volume_number: 1
      total_pages: 500
      base_file: v001.txt
